server:
  port: 8080

name: liming495

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

spring:
  security:
    user:
      name: user
      password: password

security:
  oauth2:
    client:
      clientId: a-service
      clientSecret: 123456
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server