server:
  port: 5000
  servlet:
    context-path: /uaa

eureka:
  client:
    instance:
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: ${server.servlet.context-path}/actuator/health

spring:
  datasource:
    url: jdbc:postgresql://db:5432/tiny2
    username: tiny2
    password: A5p7P4
    driverClassName: org.postgresql.Driver
    schema:
      - classpath:schema.sql
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  redis:
    database: 0
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: 50000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1