server:
  port: 5000
  servlet:
    context-path: /uaa

management:
  security:
    enabled: false
  context-path: /mgmt

eureka:
  instance:
    health-check-url-path: ${server.servlet.context-path}${management.context-path}/health
    status-page-url-path: ${server.servlet.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.servlet.context-path}${management.context-path}

spring:
  datasource:
    url: jdbc:postgresql://db:5432/tiny2
    username: tiny2
    password: A5p7P4
    driverClassName: org.postgresql.Driver
    schema:
      - classpath:schema.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  redis:
    database: 0
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: 50000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1