server:
  port: 8060

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: a-service
          uri: lb://A-SERVICE
          predicates:
            - Path=/a/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: b-service
          uri: lb://B-SERVICE
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: d1-service
          uri: lb://D1-SERVICE
          predicates:
            - Path=/d/1/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: d2-service
          uri: lb://D2-SERVICE
          predicates:
            - Path=/d/2/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: d3-service
          uri: lb://D3-SERVICE
          predicates:
            - Path=/d/3/**
          filters:
            - StripPrefix=1
            - RequestTime=true