version:  '2'
services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tiny2
      POSTGRES_DB: tiny2
      POSTGRES_PASSWORD: A5p7P4
      PGDATA: /var/lib/postgresql/data/pgdata
      volumes: /home/server/pg_data/data:/var/lib/postgresql/data/pgdata
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15673:15672
  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
  registry:
    image: tiny2/registry
    ports:
      - "8761:8761"
  config:
    image: tiny2/config
    ports:
      - "8888:8888"
  monitor:
    image: tiny2/monitor
    ports:
      - "8040:8040"
  gateway:
    image: tiny2/gateway
    ports:
      - "8060:8060"
  auth-service:
    image: tiny2/auth-service
    ports:
      - "5000:5000"
    depends_on:
      - 'db'
      - 'redis'
  a-service:
    image: tiny2/a-service
  b-service:
    image: tiny2/b-service
  d1-service:
    image: tiny2/d1-service
  d2-service:
    image: tiny2/d2-service
  d3-service:
    image: tiny2/d3-service
  service-e:
    image: tiny2/service-e